# Parameter set for outdoor environment (e.g. short experiment sequence of the Newer College Dataset)

# topic: (set in launch file or command line)
deskew: false
max_range: 120.0
min_range: 0.5
voxel_size: 0.6
max_points_per_voxelized_scan: 2200
min_points_per_voxelized_scan: 1500
planarity_threshold: 0.15
max_points_per_voxel: 3
initial_threshold: 2.0
min_motion_th: 0.1
max_num_iterations: 50
convergence_criterion: 0.0001
